#!/bin/sh
set -e

PKG=deltafeedback

if [ -d /run/systemd/system ]; then
    systemctl stop    $PKG.service 2>/dev/null || true
    systemctl disable $PKG.service 2>/dev/null || true
fi

#DEBHELPER#
exit 0
